# Theme settings
LIGHT_THEME = "sandstone"
DARK_THEME = "superhero"

# Font settings
HEADER_SIZE = 20
SUBHEADER_SIZE = 16
TEXT_SIZE = 12
FONT_FAMILY = 'Arial'

# UI settings
BUTTON_WIDTH = 25
BUTTON_SIZE = 12
GEOMETRY = "800x800"

# Audiogram settings
COLOR_LEFT = 'blue'
COLOR_RIGHT = 'firebrick'
COLOR_BINAURAL = 'black'
LINE_WIDTH = 1.5
MARKER_SIZE = 12
NOT_HEARD_MARKER_SIZE = 25
MARKER_EDGE_WIDTH = LINE_WIDTH
SHIFT = 0.4
MARKER_LEFT = 'x'
MARKER_RIGHT = 'o'
MARKER_BINAURAL = 'x'
NOT_HEARD_MARKER = '|'
NOT_HEARD_LEFT_MARKER = '3'
NOT_HEARD_RIGHT_MARKER = '4'

LABEL_FONT_SIZE = 12
LEGEND_FONT_SIZE = 12
TICK_FONT_SIZE = 10
TEXT_FONT_SIZE = 9